Feature delete card
wory04/proman-javascript pull request #13
Opened 2019-09-30 13:01 UTC by MParoczi

2019-10-01 12:59 UTC, jsonfly requested changes
Alapvetően tök jó lett és működik is szépen, néhány dolgot javasoltam csak. És magyarul írtam mindent most, néha így szoktam. :)
🥇

2019-10-01 12:59 UTC, jsonfly commented on main.py
> +        return data_handler.delete_card(card_data)
ez is egy jó megoldás, de egy 204-es státuszkód üres body-val is elég lenne, hiszen a frontend tud arról, hogy melyik card törlését kérte, így elég a siker tényét jelezni, utána tudni fogja, hogy melyik card-ot kell kivennie a dom-ból

2019-10-01 12:59 UTC, jsonfly commented on db_common.py
> +                    RETURNING *
ezt nem is ismertem, szép megoldás

2019-10-01 12:59 UTC, jsonfly commented on main.py
>  def rename_card(id):
ez a függvény azt az egy dolgot csinálja, amire a neve utal? :) (tudom, gonosz a kérdés, és nehéz is szépen elnevezni...)

2019-10-01 12:59 UTC, jsonfly commented on static/js/data_handler.js
> +            body: JSON.stringify(data),
REST szerint a delete endpoint az url-ből kéne, hogy kiolvassa az id-t, tehát pl. a http://127.0.0.1:5000/card/56 az 56-os id-jú kártyát törli. Ez esetben viszont nem kell a body-ban küldeni semmit, mert nincs szüksége a szervernek több infóra, csak az id-ra.

2019-10-01 12:59 UTC, jsonfly commented on static/js/dom.js
> +        let cardContainer = document.querySelector(`.card[id="${cardData.id}"`).parentElement;
ebbe a sorba azt akartad írni, hogy `let cardContainer = cardToRemove.parentElement`?

2019-10-01 12:59 UTC, jsonfly commented on static/js/dom.js
> +        let cardToRemove = document.querySelector(`.card[id="${cardData.id}"`);
ilyen esetekben, amikor soha nem kap új értéket a "változód", lehet const-ot használni let helyett

2019-10-01 12:59 UTC, jsonfly commented on static/js/dom.js
> +    addEventListenersToCard: function(currentCard) {
jó elnevezés, tetszik

2019-10-02 07:39 UTC, MParoczi commented
Köszönöm szépen a review-t Gábor!

A következőket módosítottam az ajánlásaid alapján:
- átneveztem a rename_card függvényt a main.py-ban
- a delete endpoint most már az URL-ből szerzi meg törölni kívánt kártya id-ját, és most már nincs a delete metódusnak body-ja
- módosítottam a fölösleges querySelector részt
- cseréltem a let statement-et const-ra

Ahogy tegnap végül megbeszéltük személyesen, a kód a törlés során még mindig az adatbázis által visszaadott információ alapján törli a kártyát a DOM-ból.

2019-10-03 10:11 UTC, jsonfly commented on static/js/dom.js
> +        let cardContainer = cardToRemove.parentElement;
igazából ez a let is lehet const akár

2019-10-03 13:36 UTC, merged